export const home = "/"
export const property_list = "/property-list"
export const agent = "/agent"
export const review = "/review"
export const message = "/message"
export const my_profile = "/my-profile"